on: [push, pull_request, pull_request_target]

name: Lint

jobs:
  restore-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 -B -m unittest discover -s tests -v

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shellcheck
        uses: ludeeus/action-shellcheck@1.1.0
        env:
          SHELLCHECK_OPTS: -e SC1091,SC1117,SC2001,SC2034

  shfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mfinelli/setup-shfmt@v3
      - run: bash -n wireguard-install.sh && bash -n wireguard-backup.sh
      - run: shfmt -d wireguard-install.sh wireguard-backup.sh
